name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    # Skip automated code review for draft PRs
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Cursor CLI
        run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: Configure git identity
        run: |
          git config user.name "Cursor Agent"
          git config user.email "cursoragent@cursor.com"

      - name: Perform automated code review
        timeout-minutes: 3
        continue-on-error: true
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          MODEL: gpt-5
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cursor-agent --force --model "$MODEL" --output-format=text --print 'Automated code review for PR #${{ github.event.pull_request.number }} in ${{ github.repository }}.

          CRITICAL: Complete ALL tasks below, then IMMEDIATELY terminate. Do not continue after submitting the review.

          Tasks (execute in order):
          1. Get existing comments: gh pr view --json comments
          2. Get diff: gh pr diff  
          3. Review diff for high-severity issues only
          4. Submit review: gh pr review --comment
          5. TERMINATE IMMEDIATELY

          Rules:
          - Max 5 inline comments (only critical issues)
          - One issue per comment on exact changed line
          - Use emojis: 🚨 Critical 🔒 Security ⚡ Performance ⚠️ Logic
          - Skip if similar feedback exists nearby
          - Reply "✅ Resolved" if issue appears fixed

          After submitting review, type: "Review complete. Terminating." and exit.'
